# Generated by Django 5.1.15 on 2026-09-02 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_customuser_avatar_customuser_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountCOA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_akun', models.CharField(max_length=20)),
                ('nama_akun', models.CharField(max_length=255)),
                ('kategori_akun', models.CharField(choices=[('Cash & Bank', 'Cash & Bank'), ('Accounts Receivable (A/R)', 'Accounts Receivable (A/R)'), ('Inventory', 'Inventory'), ('Other Current Assets', 'Other Current Assets'), ('Fixed Assets', 'Fixed Assets'), ('Depreciation & Amortization', 'Depreciation & Amortization'), ('Other Assets', 'Other Assets'), ('Accounts Payable (A/P)', 'Accounts Payable (A/P)'), ('Other Current Liabilities', 'Other Current Liabilities'), ('Long Term Liabilities', 'Long Term Liabilities'), ('Equity', 'Equity'), ('Income', 'Income'), ('Cost of Sales', 'Cost of Sales'), ('Expenses', 'Expenses'), ('Other Income', 'Other Income'), ('Other Expense', 'Other Expense')], max_length=50)),
                ('pengguna', models.CharField(default='all', max_length=100)),
                ('pajak', models.CharField(blank=True, default='', max_length=50)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coa_accounts', to='accounts.company')),
            ],
            options={
                'ordering': ['kode_akun'],
                'unique_together': {('company', 'kode_akun')},
            },
        ),
    ]
