# Generated by Django 5.1.15 on 2026-09-09 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_coa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountcoa',
            name='deskripsi_pajak',
            field=models.TextField(blank=True, default=''),
        ),
    ]
