# Generated by Django 5.1.15 on 2026-09-02 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_lead_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='next_follow_up',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
