# Generated by Django 5.1.15 on 2026-09-02 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_alter_activitylog_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='activity_type',
            field=models.CharField(choices=[('CALL', 'Telepon'), ('EMAIL', 'Email'), ('MEETING', 'Meeting'), ('NOTE', 'Catatan'), ('FOLLOW_UP', 'Follow Up')], default='NOTE', max_length=20),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
